package options

const (
	HeaderFlagName                = "header"
	AWSSigV4FlagName              = "aws-sigv4"
	AWSRegionFlagName             = "aws-region"
	DataStringFlagName            = "data"
	DataStdinFlagName             = "data-stdin"
	DataFileFlagName              = "data-file"
	DataURLEncodeFlagName         = "data-urlencode"
	FormatFlagName                = "format"
	OutfileFlagName               = "outfile"
	FailFlagName                  = "fail"
	DetailsFlagName               = "details"
	TimeoutFlagName               = "timeout"
	VerboseFlagName               = "verbose"
	NoFollowRedirectsFlagName     = "no-follow-redirects"
	AliasHeadingFlagName          = "no-heading"
	CertfileFlagName              = "cert"
	CertkeyFlagName               = "key"
	CertKindFlagName              = "cert-kind"
	CertPassFlagName              = "cert-pass"
	TLSTraceFlagName              = "tls-trace"
	TLSMinVersionFlagName         = "tls-min-version"
	TLSMaxVersionFlagName         = "tls-max-version"
	TLSInsecureSkipVerifyFlagName = "tls-skip-verify-insecure"
)
