name: Go

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Check formatting
      run: |
        go fmt ./...
        git diff --exit-code
        
    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./...
